version: '3'
services:
  vite_app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
